use_frameworks!

platform :ios, '10.0'

target 'XxCocoapodsPackage_Example' do
  pod 'XxCocoapodsPackage', :path => '../'

  target 'XxCocoapodsPackage_Tests' do
    inherit! :search_paths

    
  end
end
